Infection state
mehta-lab/VisCy pull request #118
Opened 2024-07-29 21:03 UTC by alishbaimran

2024-07-29 22:41 UTC, ziw-liu requested changes

2024-07-29 22:41 UTC, ziw-liu commented on applications/contrastive_phenotyping/graphs_ConvNeXt_ResNet.py
> +<<<<<<< HEAD
Merge error

2024-07-29 23:42 UTC, ziw-liu commented on applications/contrastive_phenotyping/graphs_ConvNeXt_ResNet.py
> +=======
merge error

2024-07-31 20:17 UTC, ziw-liu commented on viscy/data/hcs.py
> +warnings.filterwarnings("ignore", message="To copy construct from a tensor")
```suggestion
```
Don't filter this warning.

2024-07-31 20:21 UTC, ziw-liu commented on applications/contrastive_phenotyping/training_script.py
> +main(args)
Will DDP work without a guard?

2024-07-31 20:30 UTC, ziw-liu commented on viscy/data/triplet.py
> +        num_fovs: int = 4, # for quick testing
Remove these comments

2024-07-31 20:31 UTC, alishbaimran commented on applications/contrastive_phenotyping/training_script.py
> +main(args)
causes some issues

2024-07-31 20:31 UTC, ziw-liu commented on viscy/data/triplet.py
> +            fit=False, #prediction dataset where fit is False
```suggestion
            fit=False,
```

2024-07-31 20:32 UTC, ziw-liu commented on viscy/light/engine.py
> +        _, positiveProjection = self.model(pos_img)
Variables should be snake_case.

2024-07-31 20:35 UTC, ziw-liu commented
Please refer to [the contributing guide](https://github.com/mehta-lab/VisCy/blob/main/CONTRIBUTING.md#ci-requirements) for CI requirements.

2024-07-31 20:54 UTC, ziw-liu commented on viscy/data/triplet.py
> +        num_fovs: int = 4,
Is this needed in prod or just for debugging?

2024-07-31 20:59 UTC, ziw-liu approved these changes

2024-07-31 23:13 UTC, merged